/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPrincipal;

import despachoabogados.DespachoAbogados;

/**
 *
 * @author 1GDAW02
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mAltaAbogado = new javax.swing.JMenuItem();
        mBajaAbogado = new javax.swing.JMenuItem();
        mModificacionAbogado = new javax.swing.JMenuItem();
        mConsultaAbogados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mAltaCasos = new javax.swing.JMenuItem();
        mBajaCaso = new javax.swing.JMenuItem();
        mModificacionCaso = new javax.swing.JMenuItem();
        mConsultaCaso = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mAltaClientes = new javax.swing.JMenuItem();
        mBajaClientes = new javax.swing.JMenuItem();
        mModificacionClientes = new javax.swing.JMenuItem();
        mConsultaClientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Abogados");

        mAltaAbogado.setText("Alta");
        mAltaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaAbogadoActionPerformed(evt);
            }
        });
        jMenu3.add(mAltaAbogado);

        mBajaAbogado.setText("Baja");
        mBajaAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBajaAbogadoActionPerformed(evt);
            }
        });
        jMenu3.add(mBajaAbogado);

        mModificacionAbogado.setText("Modificación");
        mModificacionAbogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificacionAbogadoActionPerformed(evt);
            }
        });
        jMenu3.add(mModificacionAbogado);

        mConsultaAbogados.setText("Consulta");
        mConsultaAbogados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaAbogadosActionPerformed(evt);
            }
        });
        jMenu3.add(mConsultaAbogados);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Casos");

        mAltaCasos.setText("Alta");
        mAltaCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaCasosActionPerformed(evt);
            }
        });
        jMenu2.add(mAltaCasos);

        mBajaCaso.setText("Baja");
        mBajaCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBajaCasoActionPerformed(evt);
            }
        });
        jMenu2.add(mBajaCaso);

        mModificacionCaso.setText("Modificación");
        mModificacionCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificacionCasoActionPerformed(evt);
            }
        });
        jMenu2.add(mModificacionCaso);

        mConsultaCaso.setText("Consulta");
        mConsultaCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaCasoActionPerformed(evt);
            }
        });
        jMenu2.add(mConsultaCaso);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Clientes");

        mAltaClientes.setText("Alta");
        mAltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaClientesActionPerformed(evt);
            }
        });
        jMenu4.add(mAltaClientes);

        mBajaClientes.setText("Baja");
        mBajaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBajaClientesActionPerformed(evt);
            }
        });
        jMenu4.add(mBajaClientes);

        mModificacionClientes.setText("Modificación");
        mModificacionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificacionClientesActionPerformed(evt);
            }
        });
        jMenu4.add(mModificacionClientes);

        mConsultaClientes.setText("Consulta");
        mConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaClientesActionPerformed(evt);
            }
        });
        jMenu4.add(mConsultaClientes);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenu5.add(mSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAltaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaAbogadoActionPerformed
        DespachoAbogados.vistaAltaAbogado();
    }//GEN-LAST:event_mAltaAbogadoActionPerformed

    private void mBajaAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBajaAbogadoActionPerformed
        DespachoAbogados.vistaBajaAbogado();
    }//GEN-LAST:event_mBajaAbogadoActionPerformed

    private void mModificacionAbogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificacionAbogadoActionPerformed
        DespachoAbogados.vistaModificarAbogado();
    }//GEN-LAST:event_mModificacionAbogadoActionPerformed

    private void mConsultaAbogadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaAbogadosActionPerformed
        DespachoAbogados.vistaConsultarAbogado();
    }//GEN-LAST:event_mConsultaAbogadosActionPerformed

    private void mAltaCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaCasosActionPerformed
    
    }//GEN-LAST:event_mAltaCasosActionPerformed

    private void mBajaCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBajaCasoActionPerformed
    
    }//GEN-LAST:event_mBajaCasoActionPerformed

    private void mModificacionCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificacionCasoActionPerformed
    
    }//GEN-LAST:event_mModificacionCasoActionPerformed

    private void mConsultaCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaCasoActionPerformed
    
    }//GEN-LAST:event_mConsultaCasoActionPerformed

    private void mAltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaClientesActionPerformed
        DespachoAbogados.vistaAltaCliente();
    }//GEN-LAST:event_mAltaClientesActionPerformed

    private void mBajaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBajaClientesActionPerformed
        DespachoAbogados.vistaBajaCliente();
    }//GEN-LAST:event_mBajaClientesActionPerformed

    private void mModificacionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificacionClientesActionPerformed
        DespachoAbogados.vistaModificarCliente();
    }//GEN-LAST:event_mModificacionClientesActionPerformed

    private void mConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaClientesActionPerformed
        DespachoAbogados.vistaConsultarCliente();
    }//GEN-LAST:event_mConsultaClientesActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        DespachoAbogados.terminar();
    }//GEN-LAST:event_mSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAltaAbogado;
    private javax.swing.JMenuItem mAltaCasos;
    private javax.swing.JMenuItem mAltaClientes;
    private javax.swing.JMenuItem mBajaAbogado;
    private javax.swing.JMenuItem mBajaCaso;
    private javax.swing.JMenuItem mBajaClientes;
    private javax.swing.JMenuItem mConsultaAbogados;
    private javax.swing.JMenuItem mConsultaCaso;
    private javax.swing.JMenuItem mConsultaClientes;
    private javax.swing.JMenuItem mModificacionAbogado;
    private javax.swing.JMenuItem mModificacionCaso;
    private javax.swing.JMenuItem mModificacionClientes;
    private javax.swing.JMenuItem mSalir;
    // End of variables declaration//GEN-END:variables
}
